pkgname = "models"
output = "database/models"
debug = false
add-global-variants = false
add-panic-variants = false
add-soft-deletes = true
no-tests = true
no-context = true
no-hooks = true
wipe = true

[psql]
user = "johan"
host = "localhost"
port = 5432
dbname = "oikotie"
sslmode = "disable"
pass = "password"
blacklist = ["schema_migrations", "spatial_ref_sys"]
